version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/$IMAGE_REPO_NAME
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
      - java -version
      - gradle -version
      - echo Installing gradle
      - wget https://services.gradle.org/distributions/gradle-7.1.1-bin.zip
      - unzip -d /opt/gradle gradle-7.1.1-bin.zip
  pre_build:
    commands:
      - echo Entering pre build
  build:
    commands:
      - /opt/gradle/gradle-7.1.1/bin/gradle clean
      - /opt/gradle/gradle-7.1.1/bin/gradle clean build
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Entering post build
artifacts:
  files:
    - '**/*'
  base-directory: build/libs/
  discard-paths: no