com:
  ekinsol:
    jwt:
      aws:
        userPoolId: "us-east-1_t0NwjXiUy"
        region: "us-east-1"

spring:
  datasource:
    url: jdbc:postgresql://rdsdev-default.chuy89usllmn.us-east-1.rds.amazonaws.com:5432/rdsdev
    username: dev
    password: dev
    driver-class-name: "org.postgresql.Driver"
  flyway:
    locations: "classpath:db/migration"

flyway:
  locations: "classpath:db/migration"


ekinsol:
  s3:
    bucketName: comet2-infra-tfstate
    objectKey: test
    kmsKeyId: test
    region: us-east-1


aws:
  access_key_id: AKIASLFRVI3PX4CJXQ5T
  secret_access_key: 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
  s3:
    region : us-east-1
