com:
  ekinsol:
    jwt:
      aws:
        userPoolId: "us-east-1_t0NwjXiUy"
        region: "us-east-1"

spring:
  datasource:
    url: jdbc:postgresql://rdsdev-default.chuy89usllmn.us-east-1.rds.amazonaws.com:5432/rdsdev
    username: dev
    password: dev
    driver-class-name: "org.postgresql.Driver"
  flyway:
    locations: "classpath:db/migration"

flyway:
  locations: "classpath:db/migration"
