com:
  ekinsol:
    jwt:
      aws:
        userPoolId: "us-east-1_t0NwjXiUy"
        region: "us-east-1"
server:
  port: 8081
spring:
  jpa:
    properties:
      hibernate:
        dialect: com.ekinsol.challenge.apiservice.hibernate.ext.CustomHibernatePostgreSqlDialect
    hibernate:
      show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/rdsdev
    username: postgres
    password: admin123
    driver-class-name: "org.postgresql.Driver"
  flyway:
    locations: "classpath:db/migration"
  mail:
    host: http://mailhog.ekinsolutions.io/
    username:
    password:
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          port: 587
          auth: true
          startttls:
            enable: true
            required: true



flyway:
  locations: "classpath:db/migration"


ekinsol:
  s3:
    bucketName: comet2-infra-tfstate
    objectKey: test
    kmsKeyId: test
    region: us-east-1

from:
  email:
    address: dkarnati@ekinsol.com

aws:
  access_key_id: AKIASLFRVI3PX4CJXQ5T
  secret_access_key: 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
  s3:
    region: us-east-1

management:
  metrics:
    export:
      wavefront:
        sender:
          max-queue-size:


